### ISSUE TITLE
v0.2 todo list

### ISSUE THREAD

**Issue by berk-karaal** [berk-karaal/ppager#1]
- [x] Use `argparse` in `run_pager.py` #2 
    - This PR also added stdin support for Linux
- [ ] Use something like [readthedocs](https://readthedocs.org/) for documentation hosting
- [ ] Enhance `__init__.py` for easier imports
